
// V14 official 2026 event catalog. Payment remains intentionally deferred.
(function(){
 const EVENT_KEY='FAA_SELECTED_EVENT_V14';
 let events=[],selectedId=localStorage.getItem(EVENT_KEY)||'';
 const api14=async(p,o={})=>{o.headers=Object.assign({'Content-Type':'application/json'},o.headers||{});const t=localStorage.getItem('FAA_TOKEN');if(t)o.headers.Authorization='Bearer '+t;const r=await fetch(p,o);let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw Error(d.error||'Request failed');return d};
 const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const fmtDate=x=>{const d=new Date(x+'T12:00:00');return d.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})};
 const flyer=e=>e.id==='evt_garage_grinder_2'?'flyer-garage-grinder.jpg':e.id==='evt_lucky_u_motorcycle_pull'?'flyer-lucky-u.jpg':'flyer-state-championship.jpg';
 const eventById=id=>events.find(e=>e.id===id)||events[0];
 function selectEvent(id){selectedId=id;localStorage.setItem(EVENT_KEY,id);renderEventDetail(eventById(id));}
 function renderEventDetail(e){if(!e)return;const d=e.divisions||e.weightClasses||[];document.getElementById('eventDetails').innerHTML=`<button class="cta outline" data-go="events">← EVENTS</button><div class="hero card"><img src="${flyer(e)}" class="full-art"><div class="body"><span class="pill open">${esc(e.status==='open'?'REGISTRATION OPEN':'REGISTRATION CLOSED')}</span><h1>${esc(e.name)}</h1><div class="small"><b>${fmtDate(e.date)}</b><br>${esc(e.location)}<br>${esc(e.address)}</div><div class="record" style="margin-top:10px"><div class="stat"><strong>$${Number(e.entryFee).toFixed(0)}</strong><span>${esc(e.entryUnit||'ENTRY')}</span></div><div class="stat"><strong>${e.startTime?esc(e.startTime):'TBA'}</strong><span>START</span></div></div><button class="cta" data-register-event="${esc(e.id)}">REGISTER FOR THIS EVENT →</button></div></div><div class="card form"><h3>EVENT INFORMATION</h3><div class="small">${esc(e.description)}</div><h3>WEIGHT CLASSES</h3><div class="small">${d.map(esc).join(' • ')}</div><h3>CATEGORIES</h3><div class="small">${(e.categories||[]).map(esc).join(' • ')}</div>${e.doorsTime?`<h3>SCHEDULE</h3><div class="small">Doors: ${esc(e.doorsTime)}<br>Pulls: ${esc(e.startTime)}</div>`:''}<h3>PRIZES</h3><div class="small">${(e.prizes||[]).map(esc).join('<br>')}</div></div>`;document.querySelectorAll('[data-register-event]').forEach(b=>b.onclick=()=>{eventSelect.value=b.dataset.registerEvent;populateClasses();go('register')});}
 function renderCatalog(){const box=document.getElementById('eventCatalog');box.innerHTML=events.map(e=>`<div class="event"><img src="${flyer(e)}"><div class="body"><span class="pill ${e.status==='open'?'open':''}">${e.status==='open'?'REGISTRATION OPEN':'CLOSED'}</span><h3>${esc(e.name)}</h3><div class="small"><b>${fmtDate(e.date)}</b><br>${esc(e.location)}<br>$${Number(e.entryFee).toFixed(0)} ${esc(e.entryUnit||'entry')}</div><button class="cta outline" data-event-view="${esc(e.id)}">VIEW DETAILS</button></div></div>`).join('')||'<div class="notice">No events scheduled.</div>';document.querySelectorAll('[data-event-view]').forEach(b=>b.onclick=()=>{selectEvent(b.dataset.eventView);go('event')});}
 function renderSchedule(){document.getElementById('scheduleList').innerHTML=events.map(e=>`<div class="list"><div class="grow"><b>${esc(e.name)}</b><div class="small">${fmtDate(e.date)} • ${esc(e.location)}</div></div><b>${new Date(e.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}).toUpperCase()}</b></div>`).join('')||'<div class="notice">No events scheduled.</div>';}
 function populateClasses(){const e=eventById(eventSelect.value||selectedId);if(!e)return;selectedId=e.id;localStorage.setItem(EVENT_KEY,e.id);const opts=(e.weightClasses||e.divisions||[]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');right.innerHTML='<option value="">Select class</option>'+opts;left.innerHTML='<option value="">Select class</option>'+opts;}
 function renderEventSelect(){eventSelect.innerHTML='<option value="">Select an event</option>'+events.map(e=>`<option value="${esc(e.id)}">${esc(e.name)} — ${fmtDate(e.date)}</option>`).join('');if(eventById(selectedId)){eventSelect.value=selectedId}else if(events[0]){eventSelect.value=events[0].id;selectedId=events[0].id;localStorage.setItem(EVENT_KEY,selectedId)}populateClasses();}
 function renderHome(){const e=events[0];if(!e)return;document.getElementById('nextEventHero').innerHTML=`<img src="${flyer(e)}" class="full-art"><div class="body"><div class="red">NEXT EVENT</div><h1>${esc(e.name)}</h1><div class="small"><b>${fmtDate(e.date)}</b><br>${esc(e.location)}<br>$${Number(e.entryFee).toFixed(0)} ${esc(e.entryUnit||'entry')}</div><button class="cta" data-home-event="${esc(e.id)}">VIEW EVENT →</button></div>`;document.querySelectorAll('[data-home-event]').forEach(b=>b.onclick=()=>{selectEvent(b.dataset.homeEvent);go('event')});}
 async function loadEvents(){try{const d=await api14('/api/events');events=(d.events||[]).filter(e=>e.date>='2026-09-09').sort((a,b)=>a.date.localeCompare(b.date));renderHome();renderCatalog();renderSchedule();renderEventSelect();if(selectedId)renderEventDetail(eventById(selectedId));}catch(e){const n=document.getElementById('nextEventHero');if(n)n.innerHTML='<div class="body"><div class="notice">Unable to load the FAA schedule. Please refresh.</div></div>';}}
 eventSelect.addEventListener('change',()=>{selectedId=eventSelect.value;localStorage.setItem(EVENT_KEY,selectedId);populateClasses()});
 // Direct public registration: no member account required.
 const next=document.getElementById('next'); if(next)next.onclick=async()=>{const n=name.value.trim(),em=email.value.trim(),ph=phone.value.trim(),ct=city.value.trim(),eid=eventSelect.value,cat=document.getElementById('category')?.value||'',w=document.getElementById('weight')?.value||'',a=document.getElementById('arm')?.value||'right';if(!n||!em||!ph||!eid||!cat){msg.innerHTML='<div class="notice">Please complete all required fields.</div>';return}if((cat==='Amateur'||cat==='Pro')&&!w){msg.innerHTML='<div class="notice">Amateur and Pro require a weight class.</div>';return}const division=cat+' — '+((cat==='Amateur'||cat==='Pro')?w:'Open Class');const payload={name:n,email:em,phone:ph,city:ct,eventId:eid,category:cat,right:(a==='right'||a==='both')?division:'',left:(a==='left'||a==='both')?division:''};try{msg.innerHTML='<div class="notice">Submitting registration...</div>';const r=await fetch('/api/public-registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||'Registration failed');const e=eventById(eid);msg.innerHTML='<div class="notice"><strong>Registration complete.</strong><br><br>'+esc(n)+' is registered for <strong>'+esc(e?.name||'the selected FAA event')+'</strong>.<br>Category: <strong>'+esc(cat)+'</strong><br>Arm: <strong>'+esc(a==='both'?'Right and Left Arms':a==='left'?'Left Arm':'Right Arm')+'</strong>'+(cat==='Amateur'||cat==='Pro'?'<br>Weight Class: <strong>'+esc(w)+'</strong>':'')+'<br><br>Your registration has been saved. Payment will be connected at the final launch stage.</div>';next.textContent='REGISTRATION SAVED ✓';next.disabled=true}catch(e){msg.innerHTML='<div class="notice">'+esc(e.message)+'</div>'}};
 loadEvents();
})();
